[versions]
paper = "1.21.11-R0.1-SNAPSHOT"
cave-crawlers = "v2.0.0"
worldedit = "7.3.18"
fawe = "2.15.1"
mythic-mobs = "5.11.2"
vault = "1.7.1"
essentials = "2.21.2"
parties-api = "3.2.16"
lamp = "4.0.0-rc.17"
triumph-gui = "3.1.14"
xseries = "13.7.0"
junit = "5.11.4"
mockito = "5.15.2"
gson = "2.11.0"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
cave-crawlers = { module = "com.github.lidanthedev:CaveCrawlers", version.ref = "cave-crawlers" }
worldedit-bukkit = { module = "com.sk89q.worldedit:worldedit-bukkit", version.ref = "worldedit" }
fawe-core = { module = "com.fastasyncworldedit:FastAsyncWorldEdit-Core", version.ref = "fawe" }
mythic-mobs = { module = "io.lumine:Mythic-Dist", version.ref = "mythic-mobs" }
vault-api = { module = "com.github.MilkBowl:VaultAPI", version.ref = "vault" }
essentials = { module = "net.essentialsx:EssentialsX", version.ref = "essentials" }
parties-api = { module = "com.alessiodp.parties:parties-api", version.ref = "parties-api" }
lamp-common = { module = "io.github.revxrsal:lamp.common", version.ref = "lamp" }
lamp-bukkit = { module = "io.github.revxrsal:lamp.bukkit", version.ref = "lamp" }
lamp-brigadier = { module = "io.github.revxrsal:lamp.brigadier", version.ref = "lamp" }
triumph-gui = { module = "com.github.lidanthedev:triumph-gui", version.ref = "triumph-gui" }
xseries = { module = "com.github.cryptomorin:XSeries", version.ref = "xseries" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
