name: build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  java-21:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/checkout@v4
        with:
          repository: lidanthedev/CaveCrawlers
          ref: e640e5111bf3e6cb12f97964f0ea07e6ccf75bfc
          path: .ci-dependencies/CaveCrawlers
          persist-credentials: false
      - uses: actions/checkout@v4
        with:
          repository: lidanthedev/CaveCrawlAddon
          ref: 54ed322a9d1ccdedbfb188bfc876baab16861ae8
          path: .ci-dependencies/CaveCrawlAddon
          ssh-key: ${{ secrets.CAVECRAWLADDON_DEPLOY_KEY }}
          persist-credentials: false
      - name: Install native compile-only APIs
        run: |
          ./.ci-dependencies/CaveCrawlers/gradlew -p .ci-dependencies/CaveCrawlers publishToMavenLocal --no-daemon
          ./.ci-dependencies/CaveCrawlAddon/gradlew -p .ci-dependencies/CaveCrawlAddon publishToMavenLocal --no-daemon
      - run: ./gradlew clean build --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: DungeonCrawlers
          path: build/libs/*.jar
